/**
 * aing Progress Tracker v0.4.0
 * Human-readable progress file + git-based checkpoints.
 * Harness Engineering: Inform axis — multi-session continuity.
 *
 * Generates `aing-progress.md` at project root for humans & agents to read.
 * @module scripts/guardrail/progress-tracker
 */

import { readState, writeState, readStateOrDefault } from '../core/state.mjs';
import { createLogger } from '../core/logger.mjs';
import { writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';

const log = createLogger('progress');

/**
 * Update the human-readable progress file.
 * @param {object} params
 * @param {string} params.feature - Current feature name
 * @param {string} params.stage - PDCA stage
 * @param {number} params.stepCurrent - Current step number
 * @param {number} params.stepTotal - Total steps
 * @param {string[]} [params.completed] - Completed items
 * @param {string[]} [params.remaining] - Remaining items
 * @param {string} [params.lastAction] - Last action taken
 * @param {string} [projectDir]
 */
export function updateProgress(params, projectDir) {
  const dir = projectDir || process.cwd();
  const progressPath = join(dir, 'aing-progress.md');
  const now = new Date().toISOString();

  const stageIcons = {
    plan: '📋', do: '⚡', check: '🔍', act: '🔄', review: '✅', completed: '🎉'
  };
  const icon = stageIcons[params.stage] || '📌';

  const pct = params.stepTotal > 0
    ? Math.round((params.stepCurrent / params.stepTotal) * 100)
    : 0;
  const bar = generateBar(pct);

  const lines = [
    `# aing Progress`,
    ``,
    `> Auto-generated by aing. Last updated: ${now}`,
    ``,
    `## Current Task`,
    `- **Feature**: ${params.feature}`,
    `- **Stage**: ${icon} ${params.stage.toUpperCase()}`,
    `- **Progress**: ${bar} ${pct}% (Step ${params.stepCurrent}/${params.stepTotal})`,
    ``
  ];

  if (params.lastAction) {
    lines.push(`## Last Action`);
    lines.push(`${params.lastAction}`);
    lines.push(``);
  }

  if (params.completed && params.completed.length > 0) {
    lines.push(`## Completed`);
    for (const item of params.completed) {
      lines.push(`- [x] ${item}`);
    }
    lines.push(``);
  }

  if (params.remaining && params.remaining.length > 0) {
    lines.push(`## Remaining`);
    for (const item of params.remaining) {
      lines.push(`- [ ] ${item}`);
    }
    lines.push(``);
  }

  lines.push(`## Session History`);

  // Append to history
  const historyPath = join(dir, '.aing', 'state', 'progress-history.json');
  const history = readStateOrDefault(historyPath, []);
  history.push({
    ts: now,
    feature: params.feature,
    stage: params.stage,
    step: `${params.stepCurrent}/${params.stepTotal}`,
    action: params.lastAction || ''
  });
  // Keep last 20 entries
  const trimmed = history.slice(-20);
  writeState(historyPath, trimmed);

  for (const entry of trimmed.slice(-5).reverse()) {
    lines.push(`- \`${entry.ts.slice(0, 19)}\` ${stageIcons[entry.stage] || '📌'} ${entry.stage} — ${entry.action || entry.step}`);
  }

  try {
    writeFileSync(progressPath, lines.join('\n'), 'utf-8');
    log.info('Progress updated', { feature: params.feature, stage: params.stage, pct });
  } catch (err) {
    log.error('Failed to write progress file', { error: err.message });
  }
}

/**
 * Get progress summary for session-start context injection.
 * @param {string} [projectDir]
 * @returns {string|null} Summary text or null if no progress
 */
export function getProgressSummary(projectDir) {
  const dir = projectDir || process.cwd();
  const historyPath = join(dir, '.aing', 'state', 'progress-history.json');
  const history = readStateOrDefault(historyPath, []);

  if (history.length === 0) return null;

  const last = history[history.length - 1];
  const stageIcons = { plan: '📋', do: '⚡', check: '🔍', act: '🔄', review: '✅', completed: '🎉' };
  const icon = stageIcons[last.stage] || '📌';

  return `[이전 세션] ${icon} ${last.feature} — ${last.stage} 단계, ${last.step} 진행. ${last.action || ''}`;
}

function generateBar(pct) {
  const filled = Math.round(pct / 10);
  const empty = 10 - filled;
  return `[${'█'.repeat(filled)}${'░'.repeat(empty)}]`;
}
