/**
 * aing Plan Manager v1.1.0
 * Creates and manages plan documents in .aing/plans/
 * Integrates with Task Manager for checklist tracking.
 * @module scripts/task/plan-manager
 */

import { createTask } from './task-manager.js';
import { createLogger } from '../core/logger.js';
import { sanitizeFeature } from '../core/path-utils.js';
import { writeFileSync, readFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const log = createLogger('plan');

interface PlanOption {
  name: string;
  pros: string[];
  cons: string[];
}

interface ReviewNote {
  reviewer: string;
  verdict: string;
  highlights: string[];
}

interface CreatePlanParams {
  feature: string;
  goal: string;
  steps: string[];
  acceptanceCriteria?: string[];
  risks?: string[];
  options?: PlanOption[];
  reviewNotes?: ReviewNote[];
  complexityScore?: number;
  complexityLevel?: string;
}

interface CreatePlanResult {
  ok: boolean;
  planPath: string;
  taskId: string;
}

interface PlanListEntry {
  file: string;
  feature: string;
}

function getPlanDir(projectDir?: string): string {
  const dir = join(projectDir || process.cwd(), '.aing', 'plans');
  mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * Create a plan document from a task description.
 * Generates both a markdown plan file and a tracked task with subtasks.
 */
export function createPlan(params: CreatePlanParams, projectDir?: string): CreatePlanResult {
  const dir = getPlanDir(projectDir);
  const date = new Date().toISOString().slice(0, 10);
  const planPath = join(dir, `${date}-${sanitizeFeature(params.feature)}.md`);

  // Build header metadata line
  const metaParts: string[] = [`**Created**: ${date}`, `**Status**: Active`, `**PDCA Stage**: Plan`];
  if (params.complexityScore !== undefined) {
    metaParts.push(`**Complexity Score**: ${params.complexityScore}`);
  }
  if (params.complexityLevel !== undefined) {
    metaParts.push(`**Complexity Level**: ${params.complexityLevel}`);
  }

  // Generate markdown plan
  const md: string[] = [
    `# Plan: ${params.feature}`,
    ``,
    ...metaParts,
    ``,
    `## Goal`,
    params.goal,
    ``,
    `## Steps`,
    ``
  ];

  for (let i = 0; i < params.steps.length; i++) {
    md.push(`${i + 1}. [ ] ${params.steps[i]}`);
  }

  if (params.acceptanceCriteria && params.acceptanceCriteria.length > 0) {
    md.push(``, `## Acceptance Criteria`);
    for (const ac of params.acceptanceCriteria) {
      md.push(`- [ ] ${ac}`);
    }
  }

  if (params.risks && params.risks.length > 0) {
    md.push(``, `## Risks`);
    for (const risk of params.risks) {
      md.push(`- ${risk}`);
    }
  }

  if (params.options && params.options.length > 0) {
    md.push(``, `## Options`);
    for (const opt of params.options) {
      md.push(``, `### ${opt.name}`);
      if (opt.pros && opt.pros.length > 0) {
        md.push(`**Pros**`);
        for (const pro of opt.pros) {
          md.push(`- ${pro}`);
        }
      }
      if (opt.cons && opt.cons.length > 0) {
        md.push(`**Cons**`);
        for (const con of opt.cons) {
          md.push(`- ${con}`);
        }
      }
    }
  }

  if (params.reviewNotes && params.reviewNotes.length > 0) {
    md.push(``, `## Review Notes`);
    for (const note of params.reviewNotes) {
      md.push(``, `### ${note.reviewer}`);
      md.push(`**Verdict**: ${note.verdict}`);
      if (note.highlights && note.highlights.length > 0) {
        md.push(`**Highlights**`);
        for (const hl of note.highlights) {
          md.push(`- ${hl}`);
        }
      }
    }
  }

  if (params.complexityScore !== undefined || params.complexityLevel !== undefined) {
    md.push(``, `## Complexity`);
    if (params.complexityScore !== undefined) {
      md.push(`- **Score**: ${params.complexityScore}`);
    }
    if (params.complexityLevel !== undefined) {
      md.push(`- **Level**: ${params.complexityLevel}`);
    }
  }

  md.push(``, `---`, `*Generated by aing Plan Manager*`);

  try {
    writeFileSync(planPath, md.join('\n'), 'utf-8');
  } catch (err: unknown) {
    log.error('Failed to write plan', { error: (err as Error).message });
    return { ok: false, planPath: '', taskId: '' };
  }

  // Create tracked task with subtasks
  const taskResult = createTask({
    title: `[Plan] ${params.feature}`,
    feature: params.feature,
    description: params.goal,
    subtasks: params.steps.map((step: string) => ({ title: step }))
  }, projectDir);

  const taskId = taskResult?.taskId || '';
  if (!taskId) {
    log.error('Plan file created but task creation failed', { planPath });
  }

  log.info(`Plan created: ${params.feature}`, { steps: params.steps.length, taskId });

  return { ok: true, planPath, taskId };
}

/**
 * Get a plan document.
 */
export function getPlan(feature: string, projectDir?: string): string | null {
  const dir = getPlanDir(projectDir);

  try {
    const files = readdirSync(dir)
      .filter((f: string) => f.endsWith('.md') && f.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace('.md', '') === sanitizeFeature(feature))
      .sort()
      .reverse();

    if (files.length === 0) return null;
    return readFileSync(join(dir, files[0]), 'utf-8');
  } catch (_) {
    return null;
  }
}

/**
 * List all plans.
 */
export function listPlans(projectDir?: string): PlanListEntry[] {
  const dir = getPlanDir(projectDir);
  try {
    return readdirSync(dir)
      .filter((f: string) => f.endsWith('.md'))
      .map((f: string) => ({
        file: f,
        feature: f.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace('.md', '')
      }));
  } catch (_) {
    return [];
  }
}
