/**
 * aing Handoff Manager — Preserves decisions and context between pipeline stages.
 * Prevents context loss during compaction by persisting stage outputs.
 * @module scripts/pipeline/handoff-manager
 */

import { writeFileSync, readFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { createLogger } from '../core/logger.mjs';
import { sanitizeFeature } from '../core/path-utils.mjs';

const log = createLogger('handoff');

/**
 * Get the handoff directory for a feature.
 * @param {string} feature
 * @param {string} [projectDir]
 * @returns {string}
 */
function getHandoffDir(feature, projectDir) {
  const dir = join(projectDir || process.cwd(), '.aing', 'handoffs', sanitizeFeature(feature));
  mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * Write a stage handoff document.
 * Captures the key decisions, outputs, and context from a pipeline stage.
 * @param {object} params
 * @param {string} params.feature — feature name
 * @param {string} params.stage — pipeline stage (team-plan, team-exec, team-verify, team-fix)
 * @param {string} params.summary — what happened in this stage
 * @param {string[]} params.decisions — key decisions made
 * @param {string[]} [params.artifacts] — file paths of outputs produced
 * @param {string[]} [params.openIssues] — unresolved issues to carry forward
 * @param {object} [params.agentOutputs] — map of agent name → output summary
 * @param {string} [params.nextStage] — expected next stage
 * @param {string} [projectDir]
 * @returns {{ ok: boolean, handoffPath: string }}
 */
export function writeHandoff(params, projectDir) {
  const dir = getHandoffDir(params.feature, projectDir);
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
  const suffix = randomBytes(3).toString('hex');
  const filename = `${params.stage}-${timestamp}-${suffix}.md`;
  const handoffPath = join(dir, filename);

  const md = [
    `# Handoff: ${params.stage}`,
    ``,
    `**Feature**: ${params.feature}`,
    `**Timestamp**: ${new Date().toISOString()}`,
    `**Next Stage**: ${params.nextStage || 'TBD'}`,
    ``,
    `## Summary`,
    params.summary,
    ``,
    `## Key Decisions`,
  ];

  for (const decision of params.decisions) {
    md.push(`- ${decision}`);
  }

  if (params.artifacts && params.artifacts.length > 0) {
    md.push(``, `## Artifacts Produced`);
    for (const artifact of params.artifacts) {
      md.push(`- ${artifact}`);
    }
  }

  if (params.agentOutputs) {
    md.push(``, `## Agent Outputs`);
    for (const [agent, output] of Object.entries(params.agentOutputs)) {
      md.push(``, `### ${agent}`, output);
    }
  }

  if (params.openIssues && params.openIssues.length > 0) {
    md.push(``, `## Open Issues (carry forward)`);
    for (const issue of params.openIssues) {
      md.push(`- ${issue}`);
    }
  }

  md.push(``, `---`, `*Generated by aing Handoff Manager*`);

  try {
    writeFileSync(handoffPath, md.join('\n'), 'utf-8');
    log.info(`Handoff written: ${params.stage}`, { feature: params.feature, path: handoffPath });
    return { ok: true, handoffPath };
  } catch (err) {
    log.error('Failed to write handoff', { error: err.message });
    return { ok: false, handoffPath: '' };
  }
}

/**
 * Read the latest handoff for a stage.
 * @param {string} feature
 * @param {string} stage
 * @param {string} [projectDir]
 * @returns {string|null} Handoff markdown content
 */
export function readHandoff(feature, stage, projectDir) {
  const dir = getHandoffDir(feature, projectDir);
  try {
    const files = readdirSync(dir)
      .filter(f => f.startsWith(stage) && f.endsWith('.md'))
      .sort()
      .reverse();
    if (files.length === 0) return null;
    return readFileSync(join(dir, files[0]), 'utf-8');
  } catch (_) {
    return null;
  }
}

/**
 * List all handoffs for a feature in chronological order.
 * @param {string} feature
 * @param {string} [projectDir]
 * @returns {Array<{ stage: string, file: string, timestamp: string }>}
 */
export function listHandoffs(feature, projectDir) {
  const dir = getHandoffDir(feature, projectDir);
  try {
    return readdirSync(dir)
      .filter(f => f.endsWith('.md'))
      .map(f => {
        const match = f.match(/^(.+)-(\d{4}-\d{2}-\d{2}T.+)\.md$/);
        return {
          stage: match ? match[1] : f.replace('.md', ''),
          file: f,
          timestamp: match ? match[2] : '',
        };
      })
      .sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  } catch (_) {
    return [];
  }
}

/**
 * Get resume context — reads the latest handoff to determine where to continue.
 * @param {string} feature
 * @param {string} [projectDir]
 * @returns {{ canResume: boolean, lastStage: string|null, nextStage: string|null, handoff: string|null }}
 */
export function getResumeContext(feature, projectDir) {
  const handoffs = listHandoffs(feature, projectDir);
  if (handoffs.length === 0) {
    return { canResume: false, lastStage: null, nextStage: null, handoff: null };
  }

  const latest = handoffs[0];
  const content = readHandoff(feature, latest.stage, projectDir);

  // Extract next stage from handoff content
  const nextMatch = content?.match(/\*\*Next Stage\*\*:\s*(.+)/);
  const nextStage = nextMatch ? nextMatch[1].trim() : null;

  return {
    canResume: true,
    lastStage: latest.stage,
    nextStage: nextStage !== 'TBD' ? nextStage : null,
    handoff: content,
  };
}
